### ISSUE TITLE
Rule FC001 contrary to Opscode recommendation

### ISSUE THREAD

**Issue by jtimberman** [acrmp/foodcritic#1]
While we're not the authoritative source of how you should write cookbooks, we do teach (in our training materials, classes, and documentation) that node attributes should be accessed by quoted string literals rather than Ruby symbols, because it is the principle of least surprise, and will always work, as a key name as a string can contain dashes (while symbols cannot). Not everyone coming to, and using Chef is a Rubyist, and the symbol syntax may be surprising or inconsistent with other languages that use hashes.

https://github.com/acrmp/foodcritic/blob/master/lib/foodcritic/rules.rb#L1-2

**Comment by pauldraper** [comment]
> a string can contain dashes (while symbols cannot)

```ruby
:'a-symbol-can-have-dashes'
```
