### ISSUE TITLE
foodcritic is trying to descend into a "spec" directory and treating it as a cookbook?

### ISSUE THREAD

**Issue by juliandunn** [acrmp/foodcritic#148]
Got this weird error while running Foodcritic on Opscode's Java cookbook within Travis. It looks like it's trying to treat the 'spec' directory as another cookbook. Ideas?

https://travis-ci.org/juliandunn/java/jobs/7971824#L122

**Comment by brodock** [comment]
can we agree on ignoring spec folder by default?

**Comment by unixorn** [comment]
And ignore the test folder too. I'm seeing it descend into test for some of my cookbooks even when I explicitly --exclude cookbookname/test.

This is using foodcritic 8.0.0.

**Comment by vinyar** [comment]
So, the big issue around this bug, is that is now blows up any pipeline created via chefdk `chef generate cookbook`. It now generates a cookbook with scafolding for delivery, and the very first commit using default scaffolding epic fails due to this bug.

Workaround is to add exceptions to the config.json of the cookbook and have delivery-truck ignore it.

**Comment by tas50** [comment]
It feels great to be able to close this one out. By default now Foodcritic excludes the spec and test directories since we know those aren't actual shared cookbooks. Not only does it make the run faster, it prevents these annoying warnings. Enjoy

**Comment by unixorn** [comment]
Thanks, @tas50!

**Comment by frezbo** [comment]
Looks like it matches attributes in one of my cookbooks:
```
chef-reantestclient (aws:rean-gov-sd)(kc)(git:RD-507)*$ foodcritic .
Checking 12 files
.x.........x
FC011: Missing README in markdown format: attributes/README.md:1
FC031: Cookbook without metadata.rb file: attributes/metadata.rb:1
FC071: Missing LICENSE file: attributes/LICENSE:1
```
Dont know why

**Comment by knightorc** [comment]
@frezbo I opened this when I tried Foodcritic 13.x.x  https://github.com/Foodcritic/foodcritic/issues/760
