### ISSUE TITLE
Consider deprecating FC0023

### ISSUE THREAD

**Issue by sethvargo** [acrmp/foodcritic#151]
We've run into a number of issues with FC0023, and I was wondering your thoughts on deprecating the rule.
1. `not_if`/`only_if` guards are not respected on definitions. However, foodcritic improperly warns. For example:
   
   ``` ruby
   if node['my-site']['enabled']
     web_app 'foo'
       # ...
     end
   end
   ```
   
   will throw a foodcritic warning, but fixing the FC warning:
   
   ``` ruby
   web_app 'foo'
     # ...
     only_if { node['my-site']['enabled'] }
   end
   ```
   
   will result in the site **always** being created, since the guard is ignored when `web_app` is a definition.
2. I don't want some things to show up in my resource list. While this affects mostly power users, the `not_if`/`only_if` guards still put the resources in the resource list, whereas surrounding the resource definition with pure Ruby prevents their edition. This is useful when navigating the resource list.
3. It violates DRY. If I have multiple "things" that should only be executed under a conditional, it feels much more natural to wrap them entirely in a conditional, rather than duplicate an `only_if` conditional across 10 consecutive resources.

/cc @jtimberman

**Comment by tas50** [comment]
This has been deprecated
