### ISSUE TITLE
Rule Proposal: Explicitly list recipe in cookbook

### ISSUE THREAD

**Issue by sethvargo** [acrmp/foodcritic#174]
It has been my experience that:

```ruby
include_recipe 'cookbook::default'
```

is superior to:

```ruby
include_recipe 'cookbook'
```

for the following reasons:

- grepabaility
- reduces new-user confusion
- more explicit

**Comment by lamont-granquist** [comment]
Its very common to see recipes doing this, I think new users really need to learn it.  We're also unlikely to deprecate that in core chef, so I think its here to stay.
