### ISSUE TITLE
FC019: force_default and force_override not allowed?

### ISSUE THREAD

**Issue by JeanMertz** [acrmp/foodcritic#181]
In a wrapper-cookbook, these two error out for me:

```ruby
node.force_override['base_system']['user']['default_password'] = password.join
node.force_default['ntp']['servers'] = %w[
  0.nl.pool.ntp.org
  1.nl.pool.ntp.org
  2.nl.pool.ntp.org
  3.nl.pool.ntp.org
  0.uk.pool.ntp.org
  1.uk.pool.ntp.org
]
```

not sure why they get caught in the FC019 rule. The error goes away if I swap both to `override` and/or `default`. Why is `force_*` not allowed in this case?

**Comment by coderanger** [comment]
Oddly `force_default!` and `force_override!` were correctly added to the Chef 12 data files, but not the non-bang versions.

**Comment by lamont-granquist** [comment]
Fixed by #364

**Comment by jschorr** [comment]
Fyi - force_override still triggers this when using foodcritic 5.0.0.

     node.force_override['server']['mgr'] = true
     FC019: Access node attributes in a consistent manner: ./recipes/default.rb:10

**Comment by lamont-granquist** [comment]
i just tested that in isolation in an empty cookbook and it does not trigger a warning on that.

that warning is most likely valid and you're using symbols somewhere else in the cookbook and are disabling FC001

**Comment by jschorr** [comment]
I don't think that I am using symbols anywhere but will double check. Thanks.

**Comment by lamont-granquist** [comment]
remember if you have an attribute file with symbols it'll trigger on recipes that use strings, it treats the whole cookbook as a unit when attempting to determine "consistency" for FC019

**Comment by kschroeder31** [comment]
I'm actually still running into this issue as well.  Tried with version 5.0.0 and 6.0.1 and am still hitting this issue when using force_override.  I can switch it to node.override and it works fine.  I feel like node.force_override should never fail if node.override works.

**Comment by lamont-granquist** [comment]
need a replication case because i failed to replicate it.

**Comment by lamont-granquist** [comment]
could use opening it as a new issue as well if its really still a problem in 6.0.1
