### ISSUE TITLE
foodcritic should offer JSON output

### ISSUE THREAD

**Issue by docwhat** [acrmp/foodcritic#202]
There are things that use the output of foodcritic in a programatic way. e.g. [Syntastic for Vim](https://github.com/scrooloose/syntastic).

It would be very handy to have JSON style output that could be consumed without having to parse the output.

Though I have to admit, the output is very parse friendly. :-)  Well, except for the extra blank line on success.

Ciao!

**Comment by kradima** [comment]
Foodcritic annotations will be available in the Chef plugin for RubyMine [soon](https://youtrack.jetbrains.com/issue/RUBY-16315). 

We'd also prefer JSON format because the output have to be parsed to highlight warnings in the editor.
