### ISSUE TITLE
new rule to enforce use of use_inline_resources

### ISSUE THREAD

**Issue by lamont-granquist** [acrmp/foodcritic#215]
use_inline_resources will be the default for Chef 12:

https://tickets.opscode.com/browse/CHEF-4942

It should be used for all LWRPs for Chef 11.  FC017 should be deprecated (and FC017 will alert incorrectly for Chef 12 after use_inline_resources is the default).  Cookbook writers should ensure that they have this turned on in all LWRPs in order to be compatible with Chef 12 default behavior.

**Comment by lamont-granquist** [comment]
Chef 12 still doesn't have use_inline_resources as the default, although the new-style resources will.

We still need this.

**Comment by tas50** [comment]
Closing this out since we actually want the opposite now with Chef 13
