### ISSUE TITLE
FC019 false positives while using string interpolation

### ISSUE THREAD

**Issue by CBarraford** [acrmp/foodcritic#218]
It seems the following triggers `FC019` warning

```ruby
    node.default['cookbook']['key'] = "value-#{myvar}"
```

While this is does NOT trigger a warning

```ruby
    node.default['cookbook']['key'] = "value-myvar"
```

It seems using string interpolation causes false positives in foodcritic

**Comment by odcinek** [comment]
Could not reproduce - neither of those warnings is triggered by examples provided.
