### ISSUE TITLE
Support to JRuby ?

### ISSUE THREAD

**Issue by bawongfai** [acrmp/foodcritic#223]
FoodCritic depends on yajl-ruby.
But since JRuby didn't and will not support Ruby C extension, running foodcritic will fail with error "C extension support is not enabled" araised from yajl-ruby library. 

Will it have a change to replace yajl-ruby with json or json_pure ?
Just a suggestion.

Reference: https://github.com/jruby/jruby/wiki/C-Extension-Alternatives

**Comment by odcinek** [comment]
Happy to look into this once chef itself supports anything else than MRI ;)
