### ISSUE TITLE
FC009: Resource attribute not recognised:

### ISSUE THREAD

**Issue by jmreicha** [acrmp/foodcritic#233]
Foodcritic is incorrectly reporting FC009 on "timeout" attribute in git resource.

Timeouts were recently added to the SCM resource - https://github.com/opscode/chef/pull/805

**Comment by kramvan1** [comment]
I also just hit this bug with execute

**Comment by michaeloa** [comment]
Encountered the exact same issue (sensitive on execute).

**Comment by ozzyogkush** [comment]
I'm getting the FC009 on the `sensitive` attribute on `execute` blocks as well.

**Comment by odcinek** [comment]
Metadata for most versions has been added on master, do you still experience this? If so, on which chef versions?
