### ISSUE TITLE
FC009 does not recognize template/helper attributes/blocks

### ISSUE THREAD

**Issue by brichins** [acrmp/foodcritic#234]
FoodCritic 3.0.3 does not appear to recognize the "helper" methods documented at http://docs.opscode.com/resource_template.html#helpers.  It raises a FC009 error when I use a template with a helper attribute/block.

Can I turn off FC009 more granularly than using a .foodcritic file which appears to turn off  for the entire cookbook?  Maybe allow .foodcritic to scope the exception like template/foo/template_name=~FC009?

**Comment by odcinek** [comment]
Missing metadata, fixed
