### ISSUE TITLE
Complain if node.save is called

### ISSUE THREAD

**Issue by mfischer-zd** [acrmp/foodcritic#235]
Cookbooks should ordinarily not call `node.save` except under very special circumstances, and Foodcritic should catch this.

The reason is that a `node.save` call made during compilation or convergence may result in an incomplete attribute state to be saved and indexed by the Chef server.  (Recall that default attributes are reset at the beginning of every Chef run; the state should not be considered complete until convergence has completed.)  This can cause other cookbooks that rely on search results to experience inconsistent behavior that is difficult to diagnose.  (The results will be incorrect from the time `node.save` is called until the node finishes convergence.)

**Comment by lamont-granquist** [comment]
Yeah shareable/community cookbooks shouldn't do this.

**Comment by tas50** [comment]
Resolved by #555
