### ISSUE TITLE
FC041 should check HTTP method before erroring

### ISSUE THREAD

**Issue by jgoldschrafe** [acrmp/foodcritic#240]
The intention of FC041 is to suggest remote_file over the use of curl or wget for downloading files. This causes false positives when using these commands to do things other than download files, like POSTing requests to HTTP APIs (e.g. Elasticsearch). This check should be augmented to verify that no alternative HTTP method is specified before warning.

**Comment by michnmi** [comment]
This is very important to be remedied.
curl description is : 
<pre><code class="markdown">curl  is a tool to transfer data from or to a server, using one of the supported protocols 
(DICT, FILE, FTP, FTPS, GOPHER, HTTP, HTTPS, IMAP, IMAPS, LDAP, LDAPS, POP3, POP3S, 
RTMP, RTSP, SCP, SFTP, SMTP, SMTPS, TELNET and  TFTP). 
The command is designed to work without user interaction.
</code></pre>
The above nowhere explicitly says that curl is used to download a file. The assumption in FC041 is against the definition of curl .
