### ISSUE TITLE
FC007 false positive on depending on the cookbook currently being parsed

### ISSUE THREAD

**Issue by stormerider** [acrmp/foodcritic#242]
If cookbook X has two recipes, A and B, and recipe B depends on recipe A, foodcritic will throw a FC007 if X/metadata.rb does not have a dependency on cookbook X. However, such circular dependencies actually cause problems and should not be implemented.

FC007 should only fire if the cookbook is external, not the cookbook currently being processed.

**Comment by odcinek** [comment]
This happens only if `name` in `metadata.rb` does not match the dir name, which is mandatory in chef 12. It warrants a separate rule.

**Comment by espoelstra** [comment]
Ran into this when mapping a cookbook into a docker container, the fix was to set `: ${COOKBOOK_NAME:=$(grep '^name' ./metadata.rb | sed "s/'//g" | awk '{ print $2 }')}` and then map  ` -v $(pwd):/cookbooks/$COOKBOOK_NAME --working-dir /cookbooks/$COOKBOOK_NAME` in the `docker run`.
