### ISSUE TITLE
Foodcritic Mixlib::Shellout Issues

### ISSUE THREAD

**Issue by naren-black** [acrmp/foodcritic#254]
Hello,
We are implementing foodcritic in our organization on all the cookbooks we write.
While getting the cookbooks 100% foodcritic certified, we are facing the following issue:

Following command needs to be executed:
system '/usr/bin/knife ssh -x XXX -P XXX "role:XXXXXX" "sudo chef-client" '

This command does ssh into a node and runs the chef-client. The output of the chef-client run on that node also needs to be visible from the node where we invoke the chef-client.

This is throwing a mixlib::shellout FC048 message and we are unable to fix it. We have tried to run this command under "execute" resource, "ruby_block" resource, "bash" resource and also we tried using all the double quotes, single quotes combinations in vain.
We also used 'Mixlib:shellout(cmd).run_command' but still it doesn't work.

The command by itself under backticks is working fine with the output also showing well.
Any help in getting this issue resolved is highly appreciated.
Thank you.

**Comment by odcinek** [comment]
Not quite sure what was the issue here. `Mixlib::ShellOut.new(cmd).run_command` is what you want, that's the point of `FC048`.
