### ISSUE TITLE
Integration with Editor or IDE

### ISSUE THREAD

**Issue by joelhandwell** [acrmp/foodcritic#258]
Integrating foodcritic with editor or IDE and run it automatically on code change would increase development efficiency. For example, findbug eclipse plugin (http://marketplace.eclipse.org/content/findbugs-eclipse-plugin#.U-US5fldWPs) proved that.

**Comment by odcinek** [comment]
A simple https://github.com/guard/guard setup might be what you're looking for. As for more IDE-specific solutions - PRs are always welcome :)
