### ISSUE TITLE
Support for a magic comment to temporarily disable a rule

### ISSUE THREAD

**Issue by evaryont** [acrmp/foodcritic#259]
Given something like:

```ruby
package 'openjdk-6-jre-lib' do
  action :install
end

package 'openjdk-6-jre' do
  action :install
end

include_recipe 'java'
```

This triggers FC005. Rightly so, but in this one particular case, I actually like the additional verbosity. I don't want to disable FC005 entirely in this cookbook, as I do want to be notified about violations in other recipes (or even elsewhere in the file). So I'm proposing this syntax (inspired by [rubocop's](https://github.com/bbatsov/rubocop/#disabling-cops-within-source-code)):

```ruby
# foodcritic:disable FC005
package 1 do
  # ...
end
package 2 do
  # ...
end
# foodcritic:enable FC005
```

**Comment by lamont-granquist** [comment]
We should have this with `# ~FC005` comments
