### ISSUE TITLE
FC023 enforcement leads to compilation errors

### ISSUE THREAD

**Issue by jgoldschrafe** [acrmp/foodcritic#263]
This is a really trivial case that breaks *spectacularly* on non-Linux platforms that don't have `node['lsb']` defined:

    apt_repository 'collectd-5.3' do
      uri 'http://ppa.launchpad.net/vbulax/collectd5/ubuntu'
      distribution node['lsb']['codename']
      components %w(main)
      key '013B9839'
      keyserver 'keyserver.ubuntu.com'
      action :add
      only_if { node['platform'] == 'ubuntu' }
    end

**Comment by odcinek** [comment]
It is a special case, and heuristics to avoid it would have to be crazy at best (if even possible). Surround `distribution` with another `if` or exempt the resource from `FC023`?
