### ISSUE TITLE
Please update yajl-ruby to ~> 1.2

### ISSUE THREAD

**Issue by antoniobeyah** [acrmp/foodcritic#267]
There is a bug in the 1.1 series of yajl-ruby which causes the build to fail on ubuntu systems.  Updating the yajl-ruby version to 1.2 fixes the bug.

Please update yajl-ruby to ~> 1.2.

Thanks!
Antonio

**Comment by odcinek** [comment]
`1.2.1` is the current stable version pulled in by the deps. I don't think we need to pin it.
