### ISSUE TITLE
How to put check on variables used for providing value to any resource atribute

### ISSUE THREAD

**Issue by loveleshsaxena** [acrmp/foodcritic#268]
Hi,
I am using Foodcritic. I am facing issue as below:

```ruby
package_remote_path = "http://xyz.com/repo/abc.txt"
package_local_path = "/var/opt"

  remote_file "ABCPackage" do
    source package_remote_path 
    path package_local_path
    action :create
  end
```
For my use case, we have put some files in our repo, which is internal and hosted on xyz.com. I want to put check that in any recipe, no one should use the Internet to download any file. All files should be downloaded from our repo only. And that repo URL may change, hence I put it in a variable and then accessing it.
While using Foodcritic, I I declare the source directly like
 `source "http://xyz.com/repo/abc.txt"`
then it is working fine. but when I declare source like 
` source package_remote_path `
it is not working.

So my query is how to use and monitor variables with Foodcritic.

**Comment by odcinek** [comment]
Not quite sure what's the issue here. The code provided does not trigger any warnings.

This might answer your question - You cannot *monitor* variables in fc. It's a static lint, not runtime inspection.
