### ISSUE TITLE
FC009 doesn't recognize log as a valid resource

### ISSUE THREAD

**Issue by wfindley** [acrmp/foodcritic#273]
FC009: Resource attribute not recognised

    if node['virtualization']['role'] == 'guest' || node['cloud']
      >>log "msg" do
        msg "This is a virtual machine and it can't see real hard drives with their S.M.A.R.T attributes.  Not installing."
        level :info
      end
      return
    end

**Comment by odcinek** [comment]
`FC009` does not recognize `msg` as a valid attribute, and rightfully so. `s/msg/message/g`.
