### ISSUE TITLE
Bad performance of FC019

### ISSUE THREAD

**Issue by lxndrp** [acrmp/foodcritic#274]
Folks,

for some of my cookbooks, `FC019` takes ages to pass:
```bash
real	1m20.332s
user	1m18.431s
sys	0m1.430s
```
Needless to say that, given the epic it takes to run, it is unusable in the context of [Guard](https://github.com/guard/guard) and friends. For the time being, I excluded the rule from my runs, but obviously this is not what I want.

I am using `foodcritic` at version 4.0.0. Any ideas?

**Comment by odcinek** [comment]
Any examples of cbs that take this long?

**Comment by lamont-granquist** [comment]
Yeah this really needs to be validated it still happens and needs a good example public cookbook to use as a replication case.
