### ISSUE TITLE
FC009 does not recognize headers as a valid attribute for remote file.

### ISSUE THREAD

**Issue by dawsmith8** [acrmp/foodcritic#275]
`FC009: Resource attribute not recognised: ./providers/default.rb:14`

This fails even when calling foodcritic with a specific Chef version including that attribute, e.g. `-c 11.16.4`

providers/default.rb:14 = 
```ruby
remote_file "downloading datomic-#{node[:datomic][:version]} to #{local_file_path}" do
    path     local_file_path
    source   datomic_download_url
    headers  Hash.new('Basic' => "Basic #{encoded_credentials}")
    owner    username
    group    username
    checksum new_resource.checksum
    action   :create
  end
```

**Comment by odcinek** [comment]
Works as expected after all the missing metadata was committed, closing.
