### ISSUE TITLE
Deprecate FC015? (converting definition to a LWRP)

### ISSUE THREAD

**Issue by zuazo** [acrmp/foodcritic#279]
Currently definitions seem to be the best approach to implement the _Accumulator Pattern_.

Citing the [`accumulator`](https://supermarket.getchef.com/cookbooks/accumulator) cookbook:

> Accumulator is a Chef primitive that allows you to collect `Chef::Resource` objects from the current `run_context`, optionally transform this collection and then provide as input for a target  _Template_ or _File_ resource.

Typical example is an SSH _authorized_keys_ cookbook, where you want to use multiple _definition_ calls but only create **one** template resource internally:

``` ruby
ssh_authorized_key 'root' do
  key 'AAAA....'
  type 'ssh-rsa'
  action :add
end

ssh_authorized_key 'root' do
  key 'BBBB....'
  type 'ssh-rsa'
  action :add
end
```

This pattern cannot be implemented easily using LWRPs or providers.

There is one example in the official documentation: [Many Recipes, One Definition](http://docs.chef.io/definitions.html#many-recipes-one-definition)

Some real examples using definitions for this pattern: [`cron_manage`](https://github.com/opscode-cookbooks/cron/blob/master/definitions/manage.rb#L30-L44), [`sk_ssh_known_hosts_entry`](https://github.com/lamont-cookbooks/sk_ssh_known_hosts/blob/master/definitions/entry.rb#L15-L44), [`sk_sysctl`](https://github.com/lamont-cookbooks/sk_sysctl/blob/master/definitions/sysctl.rb#L51-L65), [`collectd_plugin`](https://github.com/actblue-cookbooks/collectd/blob/master/definitions/collectd_plugin.rb#L32-L82), [`hosts_entry`](https://github.com/rubiojr/swift-solo/blob/master/cookbooks/hosts/definitions/hosts_entry.rb#L23-L54).

Discussed here: hw-cookbooks/graphite/issues/197

**Comment by lamont-granquist** [comment]
I dunno, I still think that the average user should not touch definitions unless they're writing an accumulator pattern.  And once you know enough to do that, you should know enough to skip the FC015 rule...

**Comment by martinb3** [comment]
For what it's worth, since reporting this, I've moved on from definitions where possible, especially for the accumulator pattern.

**Comment by tas50** [comment]
Now that we have accumulator patterns in custom resources and notification out of custom resources to the main run context, I think there's little to no reason to continue writing definitions. If someone REALLY believes they should be doing definitions, they can easily disable this rule in their CI system or in each individual cookbook using a .foodcritic file.
