### ISSUE TITLE
sensitive attribute is not recognized on execute resource

### ISSUE THREAD

**Issue by alex-slynko-wonga** [acrmp/foodcritic#289]
According to http://docs.chef.io/chef/resources.html
sensitive is common attribute for all resources

**Comment by david-crowder** [comment]
+1 to this

As for a fix, it looks like the json needs to be updated? Pehaps #294 fixes this?

**Comment by martinb3** [comment]
:+1:

**Comment by cybermerc** [comment]
This appears to also happen within template resources. Get an FC009 error anytime I utilize the use of sensitive within a template resource.

**Comment by wubrg** [comment]
+1 to fixing this.

**Comment by odcinek** [comment]
This is fixed on master
