### ISSUE TITLE
FC048 should not evaluate 'system' in user and group resources

### ISSUE THREAD

**Issue by felka** [acrmp/foodcritic#295]
Foodcritic unable to defer between value and attribute in user and group resources during evaluating FC048. Once I put attribute(node['system_user']) with boolean value test fails, but when I put boolean value (true/false) test passes.

**Comment by maoueh** [comment]
@felka why did you closed this issue? Did you resolved it somehow? Or found a workaround? It does not seem to be resolved at least in my case.

Regards,
Matt
