### ISSUE TITLE
epic-fail not working.. exit code is 0 even on warnings being show ?

### ISSUE THREAD

**Issue by thechile** [acrmp/foodcritic#296]
Hi

When testing the opscode ntp cookbook with foodcritic v 4.0.0 i get

$ foodcritic --epic-fail all ntp
FC007: Ensure recipe dependencies are reflected in cookbook metadata: ntp/recipes/default.rb:24
FC007: Ensure recipe dependencies are reflected in cookbook metadata: ntp/recipes/default.rb:46
$ echo $?
0

This should be a non-zero exit code right ? Am i doing something wrong ?

This is on a fresh install of ubuntu with chefdk installed. 

thanks
Scott

**Comment by odcinek** [comment]
`s/all/any/g` :smiley:
