### ISSUE TITLE
FC047 String Interpolation false positive

### ISSUE THREAD

**Issue by jhmartin** [acrmp/foodcritic#298]
`node.normal['fibble']["zed"] = 5` => Fine
`node.normal['fibble']["#{zed}"] = 5` => FC047

**Comment by jaymzh** [comment]
That's not a false positive. You wanted `node.normal['fibble'][zed] = 5`

That's a correct positive.

**Comment by odcinek** [comment]
It's not `FC047`, it is `FC002`.

`node.normal['fibble']["#{zed}_is_dead"] = 5` also triggers `FC002`, which still is a false positive.
