### ISSUE TITLE
FC009: Resource attribute not recognised for chef_gem comile_time attribute

### ISSUE THREAD

**Issue by dpetzel** [acrmp/foodcritic#307]
Chef as recently added a `compile_time` attribute to the `chef_gem` resource. The suggested backward compatible approach is ` compile_time false if respond_to?(:compile_time)` however this triggers FC009. It would be cool if we are using the if respond_to? trick that this rule not get flagged.

References:
* https://docs.chef.io/resource_chef_gem.html
* https://www.chef.io/blog/2015/02/17/chef-12-1-0-chef_gem-resource-warnings/

**Comment by ranjib** [comment]
i am still hitting this with chef 12.1.1 and foodcritic github/master :-/

**Comment by odcinek** [comment]
@ranjib - could you try running with `--chef-version` and report back on the results? We're defaulting to `11.16.4` right now, which will change with https://github.com/acrmp/foodcritic/pull/315 and upcoming release.

**Comment by ranjib** [comment]
@odcinek with chef-version 12.1.1 its fixed :-) . Is there a way i can make it default

**Comment by ranjib** [comment]
@odcinek got it. I changed our rake file to use chef_version: Chef::VERSION . thanks for the quick response

**Comment by odcinek** [comment]
`master` is now defaulting to `12.1.1`, as https://github.com/acrmp/foodcritic/pull/315 has been merged

**Comment by alvaromorales** [comment]
I'm running foodcritic `4.0.0` and chef `12.4.1` and still hitting this issue. 

These trigger FC009: 

```ruby
chef_gem 'foo' do
  compile_time false if respond_to?(:compile_time)
end
```

```ruby
chef_gem 'foo' do
  compile_time false
end
```

I tried downgrading to chef `12.1.1` and running `foodcritic --chef-version 12.1.1` but got the same error.

**Comment by howdoicomputer** [comment]
I'm trying to use an `# ignore` tag to prevent this warning from occurring but I still get output.

``` ruby
# ignore: FC009
chef_gem 'chef-vault' do
  # ignore: FC009
  compile_time true if respond_to?(:compile_time) # ignore: FC009
end
 ```

Am I calling the ignore syntax correctly?
