### ISSUE TITLE
Call for release?

### ISSUE THREAD

**Issue by miketheman** [acrmp/foodcritic#318]
Hello Maintainers!

We've had some time since 4.0.0 - almost a year now.

There's been some awesome updates to the codebase - namely support for Chef 12 - and I think it might also be appropriate to add a Chef 12.1.0 metadata to support the `compile_time` flag on `chef_gem` resources (triggers a `FC009: Resource attribute not recognised` error).

Is there anything I can do to help get a release done? Is there a date already on your roadmap?

Refs:
- https://github.com/acrmp/foodcritic/compare/v4.0.0...master
- https://www.chef.io/blog/2015/02/17/chef-12-1-0-chef_gem-resource-warnings/

Tagging: @jaymzh @odcinek @lamont-granquist @acrmp

**Comment by jaymzh** [comment]
@odcinek  and I were talking about doing a release recently... I was a little wary of doing one without @acrmp 's sign off. But also, I hate to hold this up.

So - I'll reach out to him in email today, and if we don't hear back in a week, we'll cut a release.

**Comment by odcinek** [comment]
https://github.com/acrmp/foodcritic/pull/315 blocker?

**Comment by coderanger** [comment]
Looks like that blocker was merged. Good time to reconsider pushing towards a 5.0 release?

**Comment by gsaslis** [comment]
yeah i'd love the 5.0 release as #172 has been a bit of a blocker for me so far..  :+1:

**Comment by chilicheech** [comment]
any update on when we'll get a new release?

**Comment by lamont-granquist** [comment]
dup of #344
