### ISSUE TITLE
FC009: 'environment' attribute in git resource triggers false positive

### ISSUE THREAD

**Issue by gdamiani** [acrmp/foodcritic#325]
If I'm not mistaken, the following resource should be acceptable chef code:
```
git '/opt/buzzfeed/taupe' do
    user 'taupe'
    group 'taupe'
    repository "git@github.com:buzzfeed/taupe.git"
    action :checkout
    timeout 600
    notifies :create, "python_virtualenv[/buzzfeed/venv]", :immediately
    notifies :run, 'execute[install-pip-packages]'
    environment { 'SSH_AUTH_SOCK' => '/tmp/ssh-agent.sock' }
end
```

the `environment` hash is valid since Chef 12:  http://docs.chef.io/resource_git.html

foodcritic false positive here, though it's not so interesting:
```
$ foodcritic ./cookbooks/taupe
FC009: Resource attribute not recognised: ./cookbooks/taupe/recipes/default.rb:45
```

Chef DK 0.4.0 / FoodCritic 4.0.0

**Comment by gravaton** [comment]
Also seeing this triggering on the 'environment' attribute in a 'git' resource.  Removing the attribute silences the false positive, but breaks the cookbook :frowning: 

Chef DK 0.5.1 / FoodCritic 4.0.0

**Comment by lamont-granquist** [comment]
will be handled through #344
