### ISSUE TITLE
Custom rule to check missing cookbook version in environments file

### ISSUE THREAD

**Issue by rajeshapt** [acrmp/foodcritic#326]
Need custom foodcritic rule to check missing cookbook version in environments file. Can anyone help

**Comment by chazzly** [comment]
I don't know about a rule, but I did write a knife plug-in called verschart ('https://rubygems.org/gems/knife-verschart') which we use to highlight missing or out of line version constraints.  I'm not trying to self-promote, honest, it's simply how we handle that situation.

**Comment by lamont-granquist** [comment]
not a bug report
