### ISSUE TITLE
Alias for --epic-fail

### ISSUE THREAD

**Issue by coderanger** [acrmp/foodcritic#327]
While the humor value of `--epic-fail` is nice, it would be good to switch to something like `--fail-tags` and have `--epic-fail` be an internal alias for people that appreciate the joke.

**Comment by jaymzh** [comment]
That's like asking to rename `ohai` to `factor` and symlink `ohai` for people who appreciate the joke. As Adam would say ... this is the delighter.

I don't really see any reason to change this.

**Comment by coderanger** [comment]
Ohai is a specific word that people learn the meaning of. The phrase "epic fail" is a particular artifact of pop culture and not super obvious to non-English-speakers.

**Comment by jaymzh** [comment]
Ohai is also pop culture... the exact same culture as epic fail (internet memes). Non-native speakers don't get the ohai reference any more than they get the epic fail reference.

That said if you feel strongly, send a PR.

**Comment by lamont-granquist** [comment]
Super low priority given the rest of the issues.
