### ISSUE TITLE
FC009 triggers false positive on user resource

### ISSUE THREAD

**Issue by philoserf** [acrmp/foodcritic#329]
Given a user resource

```
user 'username' do
  password '63e...' # a shortened 256 length string
  salt '72d...' # a shortened 64 length string
  iterations 25_000
end
```

When I run foodcritic against the cookbook I get

```
FC009: Resource attribute not recognised: /Users/philoserf/cookbooks/pair_station/recipes/users.rb:2
```

While I expect the recipe to pass

Because these attributes are included in the user resource in Chef 12.3.0 which I am running

```
def initialize(name, run_context=nil)
  super
  @resource_name = :user
  @username = name
  @comment = nil
  @uid = nil
  @gid = nil
  @home = nil
  @shell = nil
  @password = nil
  @system = false
  @manage_home = false
  @force = false
  @non_unique = false
  @action = :create
  @supports = {
    :manage_home => false,
    :non_unique => false
  }
  @iterations = 27855
  @salt = nil
  @allowed_actions.push(:create, :remove, :modify, :manage, :lock, :unlock)
end
```

**Comment by philoserf** [comment]
Hm? It looks like the attributes I am using are included:

https://github.com/acrmp/foodcritic/blob/master/chef_dsl_metadata/chef_12.1.1.json

**Comment by jaymzh** [comment]
I think this is fixed in git, but not released - are you using git or a release? We do need to cut a release..

**Comment by philoserf** [comment]
I tested was using 4.0.0.

**Comment by philoserf** [comment]
No release since June 2014 `https://github.com/acrmp/foodcritic/releases/tag/v4.0.0`
Time to roll. Anything I can do to help?

**Comment by knightorc** [comment]
+1 chef 12.4.1 and foodcritic 4.0.0

**Comment by fmonserrat** [comment]
:+1:  The same situation here chef 12.4.1 and foodcritic 4.0.0

**Comment by trilitheus** [comment]
Hitting this with
```force true```
on user resource

**Comment by lamont-granquist** [comment]
This is a constant problem, will be handled through #344
