### ISSUE TITLE
FC001 is re-enabled thus http://www.foodcritic.io/ is out-of-date

### ISSUE THREAD

**Issue by philoserf** [acrmp/foodcritic#330]
http://www.foodcritic.io/ still reflects FC001 as deprecated.

`This rule has been deprecated. See the discussion against issue #86 for more detail.`

While the Changelog and experience show it is back.

```
 - [FC001: Use strings in preference to symbols to access node attributes](http://foodcritic.io/#FC001)
+    rule re-instated
+    ([related issue](https://github.com/acrmp/foodcritic/issues/97)).
+    Thanks @sethvargo.
```

**Comment by lamont-granquist** [comment]
we nuked the old gh pages, and are working on the docs site in the docs site.
