### ISSUE TITLE
How to check attribute file using FC

### ISSUE THREAD

**Issue by loveleshsaxena** [acrmp/foodcritic#333]
Hi,
I am working for SAP Labs, we have a requirement to create a FC rule to check for attributes like attribute name should be of all small letters, with no digit or special character and words separated by underscore (like source path should be source_path and not sourcePath).
I know ruby but I am not able to figure out how to create the above rule.
Please help me on this.

Lovelesh.

**Comment by lamont-granquist** [comment]
not a bug
