### ISSUE TITLE
Foodcritic checking only default.rb recipe, not any other

### ISSUE THREAD

**Issue by loveleshsaxena** [acrmp/foodcritic#334]
Hi Andrew,
I am using foodcritic for testing cookbook. While just for testing its functionality, I copied the same code to default.rb and rhel.rb recipes. Then I execute foodcritic with the cookbook path and it is only giving the default.rb errors. Also I then tried removing the false code from default.rb and running it again, but no luck. Then I tried to run it with specific path to the recipe itself, but again no luck.
Below are some snippet of execution:

[root@mo-765b92823 ~]# foodcritic /opt/Chef/cookbooks/sms-logrotator/recipes/default.rb
FC002: Avoid string interpolation where not required: /opt/Chef/cookbooks/sms-logrotator/recipes/default.rb:28
FC009: Resource attribute not recognised: /opt/Chef/cookbooks/sms-logrotator/recipes/default.rb:20
FC011: Missing README in markdown format: /opt/Chef/cookbooks/sms-logrotator/README.md:1
FC013: Use file_cache_path rather than hard-coding tmp paths: /opt/Chef/cookbooks/sms-logrotator/recipes/default.rb:16
[root@mo-765b92823 ~]# foodcritic /opt/Chef/cookbooks/sms-logrotator/recipes/rhel.rb
FC011: Missing README in markdown format: /opt/Chef/cookbooks/sms-logrotator/README.md:1

Please help me on this.

Lovelesh.

**Comment by loveleshsaxena** [comment]
Hi Andrew,
I have one more query.
Foodcritic only checks for the values as static but not dynamically at run time?
Like the two cases of code:

1) Variable based:
source_value="/tmp/http://www.example.org/large-file.tar.gz"
remote_file "/tmp/large-file.tar.gz" do
  source source_value
end

2) Static based:
remote_file "/tmp/large-file.tar.gz" do
  source "/tmp/http://www.example.org/large-file.tar.gz"
end


In the above two cases, foodcritic is not giving me the error in 1st case, while in 2nd case it is giving me the error, on 'source' field.

Kindly suggest how to put checks on the basis of variable values.


Lovelesh.

**Comment by lamont-granquist** [comment]
This is a static analysis tool so it can't solve the second problem.

The first problem there's not enough context to know what is going on, it does work on recipes other than default.rb
