### ISSUE TITLE
FC002: Avoid string interpolation where not required

### ISSUE THREAD

**Issue by gdbtek** [acrmp/foodcritic#336]
I have following code and got the warning but I don't know how to get rid of the warning. I tried to change from `find '#{node['node-js']['install_folder']}/bin'` to `'find node['node-js']['install_folder']/bin` but still didn't work. Any thought?

```
bash "symlink-local-bin-#{node['node-js']['install_folder']}/bin" do
  code <<-EOH
    find '#{node['node-js']['install_folder']}/bin' -maxdepth 1 -xtype f -perm -u+x -exec bash -c -e '
      for file
      do
        ln -f -s "${file}" "/usr/local/bin/$(basename "${file}")"
      done' bash '{}' \\;
  EOH
  only_if { ::File.directory?("#{node['node-js']['install_folder']}/bin") }
end
```

> FC002: Avoid string interpolation where not required: cookbooks/node-js/recipes/install.rb:38

line 38 is at the `find` command

**Comment by chazzly** [comment]
Try double quotes:

find "#{node['node-js']['install_folder']}/bin" -maxdepth 1 ......

**Comment by gdbtek** [comment]
@chazzly  I tried that too but did not work!

**Comment by mfischer-zd** [comment]
+1, please fix.  There's no reason for this to be raised in here-docs that use interpolation.

**Comment by shanethehat** [comment]
I'm also getting this issue with interpolation in heredocs. It appears to only be an issue with Ruby 2.2 though, the same suite on 1.9.3, 2.0.0 and 2.1.15 is fine.

**Comment by shanethehat** [comment]
Seems that this issue has been fixed months ago in https://github.com/acrmp/foodcritic/commit/aaf7a9d3beb5975dbfd7d8b02e3de463420e9d77. Is there any chance of getting a release tagged?
