### ISSUE TITLE
FC009 chef_gem compile_time

### ISSUE THREAD

**Issue by bwvoss** [acrmp/foodcritic#339]
A few months back, [this PR was merged](https://github.com/acrmp/foodcritic/issues/307) to resolve FC009s for chef_gem compile_time use.  It worked, but not for the backwards compatibility case of using chef-sugar.  From the [chef docs](https://docs.chef.io/resource_chef_gem.html) (in the Attributes section):

```ruby
chef_gem 'gem_name' do
  compile_time true if Chef::Resource::ChefGem.instance_methods(false).include?(:compile_time)
end
```

Including that will result in a FC009.

**Comment by alvaromorales** [comment]
I'm running foodcritic `4.0.0` and chef `12.4.1` and still hitting the issue. I'm not using chef-sugar.

These trigger FC009:

```ruby
chef_gem 'foo' do
  compile_time false if respond_to?(:compile_time)
end
```

```ruby
chef_gem 'foo' do
  compile_time false
end
```

I tried downgrading to chef `12.1.1` and running `foodcritic --chef-version 12.1.1` but got the same error.

**Comment by lamont-granquist** [comment]
FC009 is hit every time core chef adds a new resource or adds a new property to a resource, this isn't specific to chef_gem and will be handled via a subtask off of #344
