### ISSUE TITLE
Create a rule that checks whether a repository has a LICENSE file

### ISSUE THREAD

**Issue by jtimberman** [acrmp/foodcritic#345]
It is a standard practice to include a LICENSE file in cookbooks that are open source to make it clear what their license is. This doesn't have to check content, but it should check that one of these exist:
- LICENSE
- LICENSE.txt
- LICENSE.md
- Copying/COPYING
- Others that may be per-license recommendations

**Comment by tas50** [comment]
Fixed by https://github.com/acrmp/foodcritic/pull/541
