### ISSUE TITLE
Cookbook version is specified in metadata

### ISSUE THREAD

**Issue by nathenharvey** [acrmp/foodcritic#347]
Every cookbook *should* include a version in the metadata file.  This is not strictly required though.  The Chef server will assign version `0.0.0` to a cookbook that is uploaded without a version.

Foodcritic should include a rule to verify that the metadata file includes a version key.

**Comment by jjasghar** [comment]
:+1: This seems not only obvious, but I know i've always assumed this. We should make a rule to check for this. :+1: 

the two things in a `metadata.rb` to make a "valid cookbook" are:
- `name`
- `version`

Even though when you do a `knife cookbook generate` the `metadata.rb` comes out with:
```
name             'awesome'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures awesome'
long_description 'Installs/Configures awesome'
version          '0.1.0'
```

**Comment by tas50** [comment]
This will be in 5.1
