### ISSUE TITLE
Chef Docs vs Foodcritic 4.x

### ISSUE THREAD

**Issue by philoserf** [acrmp/foodcritic#354]
The chef docs make a claim about deprecated rules: http://docs.chef.io/foodcritic.html

> Some Foodcritic rules have been deprecated: FC001, FC021, FC020, FC035, and FC036. FC018 deals with issues that may exist in older versions of the chef-client that pre-date this documentation.

What should the truth be? Should they be deprecated here or should the docs be corrected there? What say you?

**Comment by lamont-granquist** [comment]
FC001 needs to be re-added to the docs.
