### ISSUE TITLE
FC0037 inconsistent subscribes check

### ISSUE THREAD

**Issue by mrmarbury** [acrmp/foodcritic#355]
In the following resource, I have to use action __:run__ so FC is happy
```
execute "update-ca-certificates" do
  action :nothing
  subscribes :run, "cookbook_file[#{node['cacert']['file']}]", :immediately
end
```
In this resource though, I have to use __:create__ for FC to be happy
```
link node['cacert']['path'] + '/' + node['cacert']['hash'] do
   to node['cacert']['path'] + '/' + node['cacert']['file']
   subscribes :create, "cookbook_file[#{node['cacert']['file']}]", :immediately
end
```
Is there a reason or is it just a little bit inconsistent? I would rather use __:create__ in both. Since this is a valid action anyway.

BTW: I use the foodcritic version included in chefdk 0.7.0 (Foodcritic v4.0.0)

Cheers,
Stefan

**Comment by lamont-granquist** [comment]
:create isn't a valid action for execute, that's a legit bug in your code.  subscribes is the inverse of notifies so :run references the execute resource it is in, not the cookbook_file resource (which does support :create) that is the other side of the subscribes.
