### ISSUE TITLE
Linter should check just cookbook directories

### ISSUE THREAD

**Issue by juanje** [acrmp/foodcritic#37]
Hi Andrew,

I've seen this before, but some friends where trying Foodcritic in addition of tests and they have troubles because Foodcritic treat the non known directories as cookbooks.

I mean, Foodcritic treat every cookbook_path you pass to him as a possible cookbook, but also as a directory with cookbooks. As result of that, when one cookbook have any directory different of `attributes`, `recipes`, `resourses`, `providers`, `files` and `templates`, it try to check the directory as a cookbook.

With testing it could be a problem because we try to use `cookbbook/tests` or `cookbook/spec` and put inside the tree of tests. But when Foodcritic see the directory try to check `cookbook/tests` and raises false errors.

I didn't do a pull-request because I didn't know what you think about or what is the approach you like the most. I tried to check if the `cokkbook_path` has a `metadata.rb` (which every cookbook should has) to check if is a cookbook or a root directory for more cookbooks:

```diff

diff --git a/lib/foodcritic/linter.rb b/lib/foodcritic/linter.rb
index 0fda9c1..a9f78fd 100644
--- a/lib/foodcritic/linter.rb
+++ b/lib/foodcritic/linter.rb
@@ -155,8 +155,11 @@ module FoodCritic
       dirs.each do |dir|
         if File.directory? dir
           cookbook_glob = '{attributes,providers,recipes,resources}/*.rb'
-          files += Dir.glob(File.join(dir, cookbook_glob)) +
-            Dir.glob(File.join(dir, "*/#{cookbook_glob}"))
+          if File.exists? File.join(dir, 'metadata.rb')
+            files += Dir.glob(File.join(dir, cookbook_glob))
+          else
+            files += Dir.glob(File.join(dir, "*/#{cookbook_glob}"))
+          end
         else
           files << dir
         end
```

This works for me, but I don't know if you like the approach. Also I wasn't sure the best place to put a test for that.

Sorry for my awful explanation but I hope you'll get my point.

Cheers

**Comment by lamont-granquist** [comment]
Discussion is really stale, if its still an issue it should get re-opened as a PR
