### ISSUE TITLE
Foodcritic needs to support 12.5.0 style resources

### ISSUE THREAD

**Issue by lamont-granquist** [acrmp/foodcritic#370]
https://github.com/chef/chef/blob/d2102fdf7451029622a23883dc1fb262b9930abb/DOC_CHANGES.md#resources-made-easy

**Comment by lamont-granquist** [comment]
This is fairly high priority but I'll bet that 5.1.0 is wildly optimistic

**Comment by tas50** [comment]
We don't fail on them anymore so I'm going to close this out. If we think specific checks we want then we should open issues for each
