### ISSUE TITLE
FC017 triggers when LWRP is actually updating resources

### ISSUE THREAD

**Issue by tas50** [acrmp/foodcritic#387]
Foodcritic throws FC017: LWRP does not notify when updated when the LWRP actually performs the update.  Code throwing the warning:

https://github.com/chef-cookbooks/aws/blob/d0f8168d4307174a6a94ee24fc2b3f773a0302d4/providers/ebs_raid.rb

**Comment by tas50** [comment]
It appears that the @ sign in @new_resource.updated_by_last_action(true) is the root of the false alert here.

**Comment by lamont-granquist** [comment]
Should probably alert that setting updated_by_last_action directly is deprecated and that action code should be written using use_inline_resources and converge_by blocks.
