### ISSUE TITLE
FC016 triggers when using Chef 12.5 custom resources

### ISSUE THREAD

**Issue by tas50** [acrmp/foodcritic#395]
In the new custom resource format there is no need to specify a default action, but foodcritic alerts that one hasn't been declared.

**Comment by pkang** [comment]
I just got bit by this. Yes, the new [custom resource](https://docs.chef.io/custom_resources.html#syntax) says `the first action listed is the default action`. I'm going to need to turn this rule off in our code base. :neutral_face:.

**Comment by tas50** [comment]
You can turn it off with a .foodcritic file in the repo that contains ~FC016.  We need to fix the issue though

**Comment by pkang** [comment]
Thanks, @tas50. Done that already. Just adding my :+1:  that it shouldn't trigger when using new custom resources.

**Comment by lamont-granquist** [comment]
See also #370, there's probably more

**Comment by tas50** [comment]
This is fixed in 10.1.1
