### ISSUE TITLE
FC002 False positive?

### ISSUE THREAD

**Issue by ronlipke** [acrmp/foodcritic#411]
Getting an FC002 hit on the following line with >

````
%w(a b c d).each do |config|
  file "etc/app/conf/#{config}" do
>   content node['cookbook']["#{config}"]
    owner 'root'
    group 'root'
    mode '600'
    notifies :restart, 'service[app]'
  end
end
````

Not sure why it triggers there.  Apologize if I'm missing something obvious...

**Comment by coderanger** [comment]
`"#{config}"` is redundant, just put `config`. That's the whole point of the rule.

**Comment by ronlipke** [comment]
Thanks, that worked.  I was confused on where interpolation was needed, not the purpose of the rule per se.
