### ISSUE TITLE
FC009: Resource attribute not recognised: ./providers/xxxx.rb:50 on case sensitiveness

### ISSUE THREAD

**Issue by echandradhas** [acrmp/foodcritic#412]
Food critic flagged FC009  on the following block of code.
  windows_package 'xxxxxx' do
    source ::File.join(workingdir, ::File.basename(xxxx.download_uri))
    installer_type :custom
    options '/passive  /NoRestart'
    success_codes [0, 42, 127, 3010]
    action :install
  end.

I changed "windows_package" to Windows_Package to clear that error. Looks like it needs to be fixed. Case sensitivity should never be an issue in windows world I think.

**Comment by coderanger** [comment]
`windows_package` is a weird case because there is a version in core and a version in the windows cookbook with more features. Changing the name of the resource isn't working to work, Chef itself (or rather Ruby) is case sensitive.

**Comment by echandradhas** [comment]
I see that. Which one is the latest and likely to stick around for a while? core or cookbook?

**Comment by tas50** [comment]
There is active work being done to move the functionality in the windows cookbook into the chef-client core.  In the near future the need to include the windows cookbook for LWRPs will go away.

**Comment by coderanger** [comment]
But until that work is completed, I don't think `installer_type :custom` works in core, yes?

**Comment by echandradhas** [comment]
nope. That makes it hard if I have an exe to install. Also returns doesn't work. Documentation shows returns as working. I use it all lowercase windows_package , exempt FC and use success code. I hope this gets streamlined soon.

**Comment by tas50** [comment]
The PR to add a lot of the package functionality is being reviewed here: https://github.com/chef/chef/pull/4193

That will probably ship with 12.7

**Comment by echandradhas** [comment]
Thanks for the information.

**Comment by tas50** [comment]
I'm going to close this out since there's no way to fix this at the moment in FC.
