### ISSUE TITLE
Rule examples on homepage, comments decrease readability

### ISSUE THREAD

**Issue by sparr** [acrmp/foodcritic#416]
For some of the rules, there are two code blocks adjacent to each other:

```
# Don't do this
Foo
```

and

```
Bar
```

This would be easier to read if the second block also started with a comment line, so the equivalent lines match up horizontally. Maybe just a simple "# Do this instead"?

(FC006 has "# This is ok" solving this problem.)

**Comment by tas50** [comment]
This should get filed against the foodcritic-site repo where we track issues with the website. I'm going to close this one out here
