### ISSUE TITLE
Add documentation for ignoring specific violation of a rule

### ISSUE THREAD

**Issue by fletchowns** [acrmp/foodcritic#429]
I ran into a situation with chef rewind that violated FC023, but the use of only_if would totally change the meaning of what i was trying to do. So enforcing FC023 didn't make sense for this case.

Here's the scenario: https://gist.github.com/fletchowns/daee2d00b7eb193c3574

I wanted to ignore FC023 just for that specific violation, but didn't find a way to do it until I came across [this page](https://blog.froese.org/2013/12/16/foodcritic-comment-disable-method/) which linked back to #193. I think it would be useful to put this feature in the documentation.

**Comment by tas50** [comment]
The website has a section on using inline disables as well as the .foodcritic file now. Check it out and let me know if that could be more clear at this point
