### ISSUE TITLE
FC064 and FC065 codes not on website

### ISSUE THREAD

**Issue by hartfordfive** [acrmp/foodcritic#430]
Seems like these codes have been omitted from documentation?  Testing my chef cookbooks in TravisCI, I've received these errors:

```bash
FC064: Ensure issues_url is set in metadata: ./metadata.rb:1
FC065: Ensure source_url is set in metadata: ./metadata.rb:1
```

**Comment by GonzaloLeyton** [comment]
same issue here

**Comment by tas50** [comment]
I've updated the foodcritic-site repo and pushed the updated site.
