### ISSUE TITLE
FC033 false positives?

### ISSUE THREAD

**Issue by richardlock** [acrmp/foodcritic#449]
foodcritic 6.0.1 with chefdk 0.12.0

When running foodcritic against a recipe with template resources, I get FC033 even though the template source seems to be specified correctly.  It only removes the warning if I specify the "cookbook" property or use File.join with the "source" property.

This gives a warning:

``` ruby
template "/sw/app/#{cfg_user}/.lftp/bookmarks" do
  source '.lftp/bookmarks.erb'
  mode '0600'
  owner cfg_user
  group cfg_group
end
```

However, both of these work fine:

``` ruby
template "/sw/app/#{cfg_user}/.lftp/bookmarks" do
  source ::File.join('.lftp', 'bookmarks.erb')
  mode '0600'
  owner cfg_user
  group cfg_group
end
```

``` ruby
template "/sw/app/#{cfg_user}/.lftp/bookmarks" do
  source '.lftp/bookmarks.erb'
  cookbook cookbook_name
  mode '0600'
  owner cfg_user
  group cfg_group
end
```

Is this a bug or expected behaviour?

Thanks, Richard

**Comment by webframp** [comment]
Also seeing the same thing with chefdk 0.13.21 and foodcritic 6.1.1

```ruby
template '/etc/nginx/sites-available/default' do
  source 'default.erb'
  owner 'root'
  group 'root'
  mode '0644'
end

template '/etc/nginx/sites-available/graylog' do
  source 'graylog.erb'
  owner 'root'
  group 'root'
  mode '0644'
end
```

```
$ ls templates
-rw-rw-rw-  1 me users  965 05-04 10:05 default.erb
-rw-rw-rw-  1 me users  569 05-04 10:05 graylog.erb

**Comment by venkynarla** [comment]
I observed the same error while using the following version of foodcritic and chefdk. However, converging is successful during chef-client.

> 
foodcritic 6.3.0 
Chef Development Kit Version: 0.15.15
chef-client version: 12.11.18

**Comment by venkynarla** [comment]
@richardlock @webframp  I was able to pass over the error by keeping my config files inside "default" directory created under templates. I seemed to missed that initially in my cookbook structure.

> templates/default/setenv.sh.erb
> templates/default/log4j.erb

**Comment by tas50** [comment]
https://github.com/acrmp/foodcritic/pull/425 fixes this, but I need to fix the tests which are currently failing in that PR.

**Comment by tas50** [comment]
This should be resolved in the latest FC 9.0. Give it a try and open this back up if it's still a problem

**Comment by haidangwa** [comment]
@tas50 I'm seeing this in foodcritic v10.0.0 and also with v9.0.0 that comes embedded with chefdk 1.2.22.

**Comment by tas50** [comment]
I'll see what I can do to expand the testing there. I've been focusing on some of the backend helpers in Foodcritic and I'm realizing there's quite a few edge cases that were never account for. Stay tuned for some improvements in the 11 release

**Comment by stobias123** [comment]
Running into this issue with foodcritic 10.4.1

**Comment by tas50** [comment]
@stobias123 13.0 is the current release. Can you try it there.

**Comment by stobias123** [comment]
```
(improvement-filebeat)⚡ % foodcritic --version                                                                                                                  ~/repo
foodcritic 13.0.0
(improvement-filebeat)⚡ % foodcritic -t '~ETSY001' -t '~ETSY004' -t '~FC022' -t '~FC065' -t '~FC064' -t '~FC069' -t '~FC078' .                                  ~/repo
Checking 14 files
.......x......
FC033: Missing template file: ./recipes/install_filebeat.rb:14
(improvement-filebeat)⚡ % sed -n '14,20p' recipes/install_filebeat.rb                                                                                           ~/repo
template '/etc/filebeat/filebeat.yml' do
  source 'etc/filebeat/filebeat.yml.erb'
  owner 'root'
  group 'root'
  mode '0600'
end
(improvement-filebeat)⚡ [3] % tree templates                                                                                                                    ~/repo
templates
└── etc
    └── filebeat
        └── filebeat.yml.erb

2 directories, 1 file
```

**Comment by shoekstra** [comment]
Can confirm this still exists in 14.3.0:

```ruby
template '/etc/rsyslog.d/00-haproxy.conf' do
  source 'rsyslog/00-haproxy.conf.erb'
end
```

```
$ tree -f templates
templates
└── templates/rsyslog
    └── templates/rsyslog/00-haproxy.conf.erb
```

Moving `00-haproxy.conf.erb` to `templates/default/rsyslog/00-haproxy.conf.erb` fixes FC.

**Comment by artem-sidorenko** [comment]
...and in 15.1.0....

**Comment by KarthikNath** [comment]
in 16.2.0 as well
