### ISSUE TITLE
:before is a valid notification timer, but FC032 does not allow :before timers.

### ISSUE THREAD

**Issue by Poohblah** [acrmp/foodcritic#450]
According to the [feature for FC032](https://github.com/acrmp/foodcritic/blob/7d512af31aebbf978f1be680cc519b84cef6af30/features/032_check_for_invalid_notification_timing.feature), `:delayed`, `:immediately`, and `:immediate` are recognized as valid, but `:before` is also valid according to the [Chef docs](https://docs.chef.io/resource_common.html#timers).

**Comment by francoiskha** [comment]
Same issue in [PR #441](../pull/441)
