### ISSUE TITLE
Add documentation on ignoring rules via inline comments.

### ISSUE THREAD

**Issue by Poohblah** [acrmp/foodcritic#454]
Per https://github.com/acrmp/foodcritic/issues/115, individual rule violations can be ignored via inline comments in source code, but this isn't documented anywhere.  It took me a while and some digging through the source code to figure out that the correct way to format the comment is as follows:

    some_code_here # ~FCXXX

Where `XXX` is the number of the rule to ignore.

**Comment by tas50** [comment]
@Poohblah This should get opened up under https://github.com/acrmp/foodcritic-site/issues It is a valid bug, but I'm going to close it out in this repo

**Comment by Poohblah** [comment]
ok, i've opened https://github.com/acrmp/foodcritic-site/issues/21 :)
