### ISSUE TITLE
Rule idea: force cookbook_name usage for include_recipe self::recipe

### ISSUE THREAD

**Issue by ofir-petrushka** [acrmp/foodcritic#459]
When example_cookbook has multiple recipes it would often include on recipe in another.

A popular way looks like:
include_recipe 'example_cookbook::recipe2'

A superior way would be: 
include_recipe cookbook_name + '::recipe2'

This makes renaming the cookbook later easier.

Why?
* I've seen a common practice renaming cookbooks, when you want to indicate that you have hacked it, and are not on mainstream community cookbook.
* Unlike attributes this is a hard dependency that just breaks the cookbook when metadata is changed.  
* Copy pasting cookbooks as example.
* A way to say self. make more sense to me for this context?

Sorry if these are weak arguments and/or it's very low on the priority to do something like this.

**Comment by coderanger** [comment]
Chef already allows `include_recipe '::recipe2'` to fix this.

**Comment by ofir-petrushka** [comment]
I'd be happy to have that just the same.

**Comment by coderanger** [comment]
Not sure what you mean, you already have it. Chef has supported that syntax for a long while :) `cookbook_name + '::foo'` is incorrect and if anything we should make it a linter error.

**Comment by coderanger** [comment]
Also "things that make renaming a cookbook harder" is way out of scope for Foodcritic. The cookbook name is generally used in attribute keys, resource/provider names, and library namespaces.

**Comment by ofir-petrushka** [comment]
I meant I will be happy with a test that says change 'example_cookbook::recipe2' to '::recipe2'

resource/providers a lot of time use similar system of
  cookbook 'example_cookbook'
(or a property that contains it)

I am aware attributes would probably still contain the cookbook name as a best practice namespacing.

If you fell this is out of scope, fell free to close this. (if there a written scope definition btw?)

**Comment by lamont-granquist** [comment]
There's also a bug for supporting '::whatever' correctly i think?  At least there was, can't recall if it got fixed.
