### ISSUE TITLE
Rule idea: Avoid using '<<' for string concate

### ISSUE THREAD

**Issue by ofir-petrushka** [acrmp/foodcritic#467]
In ruby concatenating strings by '<<' over '+' was shown more efficient in a few benchmarking and logically it's lighter because of not creating another copy of the string.

In chef this creates a weird issue.

if I try to put an example:
a='/opt'
directory a
file a<<'/.something'

Result:
Directory would be ‘/opt/.something’
File would be ignored as already exists

I think this wouldn't be considered a bug in chef by the way it works, so I am thinking of a rule to warn of this issue.

Don't use:
a << b

Use:
a + b 

Because of said unexpected result.

**Comment by coderanger** [comment]
That is probably better suited to Rubocop which can do things like "warning level cops" :-/ Right now we don't have any good way to have suggestion-y things in FoodCritic so anything added has to be pretty high on the bad idea spectrum.

**Comment by tas50** [comment]
I agree with @coderanger here.  The current design of Foodcritic is pretty binary.  Something is either good or bad. We lack the concept of "things you probably shouldn't do". We also tend to stick to pure chef DSL issues, with other issues left up to Rubocop (and cookstyle which wraps rubocop).
