### ISSUE TITLE
FC003 no longer needed?

### ISSUE THREAD

**Issue by damacus** [acrmp/foodcritic#473]
As of  chef-client 11.8.0 zero/local mode are supported out of the box, and thus server functions such as search are available.

**Comment by iennae** [comment]
It'd be useful to reverse FC003, so it catches old chef-solo code to be removed rather than eliminating it entirely.

**Comment by tas50** [comment]
I'd vote we make set this rule to only alarm for older chef versions and make a new rule to remove solo checks and the use of solo search

**Comment by lamont-granquist** [comment]
I wouldn't bother with alarming on older chef versions.  That just becomes cruft, and people writing cookbooks on 12.5.0 and uploading them to supermarket should still not be encouraged to be added chef_solo specific hacks.  In that case we should just remove FC003 and turn up the new rule.

**Comment by tas50** [comment]
6 months later me has seen the light. We should in fact just remove this rule. It doesn't make sense in modern Chef design.

**Comment by lamont-granquist** [comment]
🎂

**Comment by tas50** [comment]
FC003 has been removed from master
