### ISSUE TITLE
FC033: does not recognize templates in non-default dir

### ISSUE THREAD

**Issue by AlexMorreale** [acrmp/foodcritic#476]
We like to separate our templates into specific folders if we write a LWRPs.

We get:
`FC033: Missing template: ./resources/logentries_follow.rb:16` 
for 

```
template app_name do
  path "/etc/le/conf.d/#{app_name}.conf"
  source 'logentries/base.conf.erb'
```

Obviously the template is there or our recipes wouldn't be working. Maybe this is not the standard? Issue or not? 

Thanks!

**Comment by troyready** [comment]
Also hit this today -- no source set in my template resource, and the template itself is in the top level of `templates/` (no default folder).

Possibly fixed by https://github.com/acrmp/foodcritic/pull/425 ? Someone should rebase it and test for tas50

**Comment by troyready** [comment]
@AlexMorreale I think you should close this as a dup of #449
