### ISSUE TITLE
FC047: false positive on force_default!

### ISSUE THREAD

**Issue by ofir-petrushka** [acrmp/foodcritic#477]
force_default! is a valid precedence for attribute assignment.

"Full Assignment"
node.default!['foo']['bar'] = {...}
node.force_default!['foo']['bar'] = {...}
node.normal!['foo']['bar'] = {...}
node.override!['foo']['bar'] = {...}
node.force_override!['foo']['bar'] = {...}
https://docs.chef.io/attributes.html

Might want to verify all 5 types are supported.

Seems this needs a similar fix to a previous PR that addressed 2/5 commands. (could be that the others didn't exist yet as the PR is 2 years old or so)
https://github.com/acrmp/foodcritic/pull/226

**Comment by tas50** [comment]
We shipped the fix for this
