### ISSUE TITLE
FC047: False positive on attribute used as an index

### ISSUE THREAD

**Issue by MarkGibbons** [acrmp/foodcritic#483]
node.default['nix_server']['directories']["/u/#{node['sf_rewards_enroll']['env']}"] = { }

gets FC047: Attribute assignment does not specify precedence: ./recipes/attributes.rb:13. 

This code doesn't generate an alert

a = node['sf_rewards_enroll']['env']
node.default['nix_server']['directories']["/u/#{a}"] = { }

**Comment by grimm26** [comment]
Looks like dupe of #225

**Comment by tas50** [comment]
Closing as a duplicate of #225
