### ISSUE TITLE
FC007 does not validate wrapper cookbooks

### ISSUE THREAD

**Issue by haidangwa** [acrmp/foodcritic#495]
We use wrapper cookbooks extensively and often a recipe in our wrapper calls a recipe from the upstream cookbook. Since our wrapper cookbook already specifies a `depends x` in its metadata, it is not required in the metadata of a cookbook that is consuming our wrapper cookbook.

For example:

our wrapper, called our_datadog, might declare this:
`depends 'datadog'` and a recipe does this `include_recipe 'datadog::nginx'`

Another cookbook, some_nginx_cookbook, might declare a dependency on `our_datadog`. FC007 should not trigger an offense for some_nginx_cookbook.

**Comment by tas50** [comment]
Unfortunately there isn't really a way to fix this one. You'll just have to disable this rule for that cookbook.  Foodcritic is just parsing the cookbook AST and doesn't know about true chef-isms like dependencies. It can't walk up a dep tree to make sure everything is really there.
