### ISSUE TITLE
Dependency Resolution in v6.3.0 Fails on Ruby Installations < 2.1.0

### ISSUE THREAD

**Issue by bbnathan** [acrmp/foodcritic#501]
A minor version of nokogiri was [released](https://rubygems.org/gems/nokogiri/versions/1.7.0) on 27 December 2016. It requires Ruby to be at or above version 2.1.0, whereas 1.6.8.1 requires Ruby >= 1.9.2. On hosts with a Ruby interpreter older than 2.1.0, installation of foodcritic v6.3.0 fails. See below.

---- Begin output of /opt/rubies/ruby-2.0.0/bin/gem install -V foodcritic -v 6.3.0 ----
(...)
Installing gem nokogiri-1.7.0
Downloading gem nokogiri-1.7.0.gem
GET https://repo.foo.com/artifactory/api/gems/ruby-repos/gems/nokogiri-1.7.0.gem
200 OK
STDERR: ERROR:  Error installing foodcritic:
	nokogiri requires Ruby version >= 2.1.0.
---- End output of /opt/rubies/ruby-2.0.0/bin/gem install -V foodcritic -v 6.3.0 ----
Ran /opt/rubies/ruby-2.0.0/bin/gem install -V foodcritic -v 6.3.0 returned 1

**Comment by tas50** [comment]
The latest foodcritic requires ruby 2.2.2 so this dep solving issue is no longer an issue. You'll need to upgrade to a supported ruby release as 2.0 is EOL

**Comment by bbnathan** [comment]
Due diligence was required. Thank you for looking into this.
