### ISSUE TITLE
Default generated cookbooks will always fail FC064 & FC065

### ISSUE THREAD

**Issue by charlesjohnson** [acrmp/foodcritic#503]
Any cookbook generated by chefdk will always fail FC064 & FC065:

```
➜  chef -v
Chef Development Kit Version: 1.1.16
chef-client version: 12.17.44
delivery version: master (83358fb62c0f711c70ad5a81030a6cae4017f103)
berks version: 5.2.0
kitchen version: 1.14.2

➜  chef generate cookbook baz
Generating cookbook baz

*snip*

➜  foodcritic -f correctness baz
FC064: Ensure issues_url is set in metadata: baz/metadata.rb:1
FC065: Ensure source_url is set in metadata: baz/metadata.rb:1
```

These rules arguably only apply to cookbooks being published on the Supermarket, and should probably not cause failures on cookbooks that are not destined for public consumption.

**Comment by tas50** [comment]
If a user wants to exclude supermarket rules they can exclude the supermarket tag instead of failing on any. Foodcritic is built for overall community cookbooks, which do get uploaded to the supermarket, thus why we included this rule. If that's not appropriate people will need to mix and match tags and individual rules in their pipelines to get the desired results.

**Comment by charlesjohnson** [comment]
Two questions:

First, should the supermarket rules be included in -t correctness?

Second, if we assume for a minute that having the default generated
cookbook fail tests out of the box is unacceptable, then what's the correct
way to fix that?

**Comment by nathenharvey** [comment]
Printing our failing tests is not the same as failing.  

```
$ foodcritic baz -f correctness
FC064: Ensure issues_url is set in metadata: baz/metadata.rb:1
FC065: Ensure source_url is set in metadata: baz/metadata.rb:1
$ echo $?
0
```

The default cookbook is not failing.

[The supermarket rules are not tagged with correctness]((https://github.com/acrmp/foodcritic/blob/master/lib/foodcritic/rules.rb#L847-L865)).
