### ISSUE TITLE
FC009 does not recognise flush_cache on 'package' resource

### ISSUE THREAD

**Issue by nidhishopback** [acrmp/foodcritic#504]
package "metricbeat" do
  action :install
  retries 2
  retry_delay 2
   flush_cache [ :before ]
end

throws the food critic error -> FC009: Resource attribute not recognised: sb_metricbeat/recipes/default.rb:21

**Comment by tas50** [comment]
What version of Foodcritic are you seeing this issue with?

**Comment by bowersna** [comment]
Foodcritic version: 8.1.0

Doesn't recognize `guard_interpreter :powershell_script` on `package` resource. Throws FC009.

package 'install-something' do
  action :install
  source '<path to source package>
  guard_interpreter :powershell_script
  not_if 'Test-Path ("path to test")'
end

**Comment by luke-vidler** [comment]
+1 getting this with ChefDK 1.0.3 on Fedora.

**Comment by tas50** [comment]
I'm fairly confident that Foodcritic 9.0 fixes this by including new metadata on functionality dumped from Chef 12.18. Give it a try and open this back up if you're still having issues.

**Comment by fernandoaleman** [comment]
I am getting this same exact error.

```
  package new_resource.packages do
    flush_cache [ :before ]
  end
```

Error:
`FC009: Resource attribute not recognised`

foodcritic 15.1.0

**Comment by jpmat296** [comment]
Same error for me, on package resource too.

foodcritic 14.3.0

**Comment by deploymentking** [comment]
Same error for me, on package resource too.

foodcritic 15.1.0

**Comment by danielcbright** [comment]
Verified with a customer of mine that this is still an issue, foodcritic 15.x

**Comment by haljimr** [comment]
Specifically 15.1.0, am that customer.  I was able to work around the issue by using yum_package instead of package, it appears the problem is that Foodcritic is not aware of the directive that is specific to yum usages, it's not part of the generic package resource definition.
