### ISSUE TITLE
FC026 Assumes that not_if statements are always OS commands

### ISSUE THREAD

**Issue by dsahni** [acrmp/foodcritic#509]
The FC026 ruleset fails if curly braces are used in the `not_if` statement. While this is correct behavior if the statement is an OS command (bash etc.), if the user is using ruby (eg: `File.exists?('/some/path/')`) the braces are required.

**Comment by jaymzh** [comment]
I use this all the time and don't see F026 issues... can you give example code?

**Comment by tas50** [comment]
Closing due to lack of response from the filer
