### ISSUE TITLE
FC023: Resources are still added to the ResourceCollection

### ISSUE THREAD

**Issue by jtimberman** [acrmp/foodcritic#51]
Abiding by this rule has a certain level of nuance that is important to consider, especially as Opscode and the rest of the community adds new features related to Reporting.

A resource that is conditional based on a resource attribute (i.e., `not_if` or `only_if`) still gets added to the ResourceCollection by Chef. The conditional merely means that the specified action will (or won't) be taken when the provider processes the resource. For certain kinds of resources, or behavior in recipes, it may be preferable to not have the resource in the collection at all. This is especially true when it comes to reporting.

Within the report handlers, two key pieces of data are available:

* all_resources
* updated_resources

All resources in the ResourceCollection are reported, whether they were updated or not, of course.

I do see that the `--tags` command-line option to disable particular tags, however I see this particular rule as an effect of functionality as much as style.

I'm not suggesting removal of the rule from the default set, but I'd like to hear further discussion about this rule.

**Comment by jorhett** [comment]
Here's another important reason. Consider this recipe:

```ruby
['add','update','remove','force_remove'].each do |action|
  aws_resource_tag node['ec2']['instance_id'] do
    action action
    tags   ec2_tags[action]
    not_if { ec2_tags[action].nil? }
  end
end
```

It simply doesn't work when that value isn't defined:

```
Chef::Exceptions::ValidationFailed
----------------------------------
Required argument tags is missing!
```

Fixing this so that compilation succeeds creates an FC023 from foodcritic...
