### ISSUE TITLE
New Rule Proposal: uid/gid should be integer

### ISSUE THREAD

**Issue by jaymzh** [acrmp/foodcritic#53]
Specifying a user like:

```
user "foo" do
  uid "3456"
  ...
end
```

Will cause chef to choke. FC should catch that this string is really an integer.

**Comment by lamont-granquist** [comment]
It looks like @jtimberman fixed this in core chef back in 10.14.2

https://github.com/chef/chef/commit/cc50e4b2834e4a996e922e4a23e621c9b568d283
