### ISSUE TITLE
FC001, FC019 shouldn't match on node.run_state

### ISSUE THREAD

**Issue by jtimberman** [acrmp/foodcritic#66]
`node.run_state` doesn't contain node attributes, and is a Hash, and doesn't allow for arbitrary switching between strings or symbols.

It does have uses inside cookbooks, such as for tracking transient data used by the node between recipes, for example in Opscode's `nginx::source` recipe and modules that should be compiled.

``` ruby
node.run_state[:nginx_configure_flags] =
  node.run_state[:nginx_configure_flags] | ["--add-module=#{node["nginx"]["passenger"]["root"]}/ext/nginx"]
```

Match results, e.g.:

```
FC001: Use strings in preference to symbols to access node attributes
  48|end
  49|
  50|node.run_state[:nginx_configure_flags] =
FC001: Use strings in preference to symbols to access node attributes
  51|  node.run_state[:nginx_configure_flags] | ["--add-module=#{node["nginx"]["passenger"]["root"]}/ext/nginx"]
```

**Comment by don-code** [comment]
I'm still seeing an FC001 in the most recent Foodcritic (8.1.0). It is minimally reproducible with:

```
node.run_state[:something] = 'blah'
```

Since it looks like this was originally fixed for only FC019, I'd suggest reopening.
