### ISSUE TITLE
FC022 incorrectly fires.

### ISSUE THREAD

**Issue by lps1975** [acrmp/foodcritic#69]
The spirit of FC022 is great - let folks know that if they declare resources in a loop, but never change the name of the resource, they are only actually creating ONE resource, not one for each iteration of the loop. (After Chef... 10.6 I think.)

Unfortunately, foodcritic does not properly identify all cases where the name of the resource has been
parametrized.

An example. Look at the last two lines...

```ruby
include_dir = "/some/directory"
Dir.entries(include_dir).each do |basename|
  next if ['.', '..'].include?(basename)
  fullname = "#{include_dir}/#{basename}"
  file fullname do   # <-- foodcritic thinks this is the same name each time; it's not!!
    ...
```
foodcritic bails on the above code. However, in the same file, there is a similar entry...

```ruby
filelist.each_key do |configfile|
  template "#{include_dir}/#{configfile}" do
    ...
```

Foodcritic is fine with this segment. I can only guess that it considers #{ inside of double-quotes
an indicator of parametrized names, but it forgot about the case where quotes are not used at
all...

Can this please be entered as a high-priority need-to-fix?

Thanks!

**Comment by odcinek** [comment]
Seems to be fixed on `master`, all the examples from above worked just fine.
