### ISSUE TITLE
Rule to detect nested node attributes in attributes.rb

### ISSUE THREAD

**Issue by tknerr** [acrmp/foodcritic#82]
I recently learned that using nested node attributes in attributes/default.rb is actually an antipattern (at least in Chef 10, might get resolved in Chef 11).

```
default['my_recipe']['base_dir']  = '/path/to/basedir'
default['my_recipe']['other_dir']  = "#{node['my_recipe']['base_dir']}/otherdir"
```

This looks sane at first, but as soon as you are overriding the default value for `['my_recipe']['base_dir']`, e.g.  in a role like so...

```
...
default_attributes({
  :my_recipe => {
    :base_dir => '/somewhere/else'
  }
})
...
```

...you get weird behavior when using the node attributes in the recipe:

* `node['my_recipe']['base_dir']` renders to `'/somewhere/else'` as expected
* but `node['my_recipe']['other_dir']` unexpectedly renders to `'/path/to/basedir/otherdir'`

Actually I have seen this pattern in many recipes, likely the cookbook authors are not aware of this behaviour, so a foodcritic rule would be nice for detecting this pattern and raising awareness.

See this thread on the mailing list for the full discussion:
http://lists.opscode.com/sympa/arc/chef/2012-10/msg00307.html

**Comment by odcinek** [comment]
Behavior changed a ton since this was filed, closing.
